site_name: BigData
pages:
- "Home": 'index.md'
- "Distribution Storage":
  - "HDFS": 'hdfs.md'
  - "Apache HBase": 'hbase.md'
- "Distribution Computing":
  - "Apache Spark": 'spark.md'
- "Components":
  - "Apache Ambari": 'ambari.md'
  - "Kibana": 'kibana.md'
  - "Logstash": 'logstash.md'
  - "Elasticsearch": 'elasticsearch.md'
markdown_extensions:
    - footnotes